apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-app
  namespace: itog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info
  template:
    metadata:
      labels:
        app: info
    spec:
      containers:
        - name: info
          image: wwitchqq/info-service:latest
          envFrom:
            - configMapRef:
                name: info-config
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
